version: '3.7'
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '9080:8080'
      - '8443:8443'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge
